# Generated by Django 3.2.7 on 2021-10-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_region',
            new_name='user_city',
        ),
    ]
