# Generated by Django 3.2.7 on 2021-10-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211011_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
